version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8.2-slim-buster
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: src
      - run: python -m unittest
